### PR TITLE
Make backfill resilient

### PR DESCRIPTION
**Pull request by duncanjbrown**
Objectives:

- don't overflow queues
- don't hit BQ byte limits

Hopefully this isn't too complicated.

Still to do: find out the actual byte limit and set it

### CODE REVIEW

**Comment by misaka** [comment]
Where is this 10k limit coming from?

It's just that this approach seems reasonable if we have a vague limit of about 10k, but if this _is_ a vague limit then what is the limitation, really?

**Comment by duncanjbrown** [comment]
> Where is this 10k limit coming from?

I made it up! See description. I want to experiment to confirm the actual limit — docs haven't been helpful.

**Comment by misaka** [comment]
What errors are we seeing?

**Comment by duncanjbrown** [comment]
OK I've simplified this on the basis of https://cloud.google.com/bigquery/quotas#streaming_inserts

new routine:

break everything up into 500 row bits as suggested by google
measure size before sending, and if we end up going over 10mb, split the batch

**Review by misaka — APPROVED** [review]

**Pull request merged**
